apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap-shivam
  namespace: kubernetes-cluster-shivam
  labels:
    app: backend-shivam
data:
  ELASTIC_URL: "https://34.125.249.203:9200"

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret-shivam
  namespace: kubernetes-cluster-shivam
  labels:
    app: backend-shivam
data:
  ELASTIC_PASSWORD: "ZWxhc3RpYw=="
  ELASTIC_USERNAME: "aWdLckctdkRyMW1USnpLRl83Vm0="
type: Opaque

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-shivam-deployment
  namespace: kubernetes-cluster-shivam
  labels:
    app: backend-shivam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-shivam
  template:
    metadata:
      labels:
        app: backend-shivam
    spec:
      containers:
        - name: backend-shivam
          image: nagpshivam/ecom-backend:latest
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          envFrom:
          - configMapRef:
              name: backend-configmap-shivam
          - secretRef:
              name: backend-secret-shivam

---

apiVersion: v1
kind: Service
metadata:
  name: backend-shivam
  namespace: kubernetes-cluster-shivam
spec:
  type: LoadBalancer
  selector:
    app: backend-shivam
  ports:
  - targetPort: 5000
    port: 81
    protocol: TCP
    nodePort: 30081
